---
namespace: "tcharl"
name: "nfs_client"
version: "1.0.1"
description: "Use freeipa capabilities to automount nfs"

authors:
  - "Charlie Mordant <cmordant1@gmail.com>"

repository: "https://github.com/OsgiliathEnterprise/nfs_client"
documentation: "https://github.com/OsgiliathEnterprise/nfs_client/blob/master/README.md"
homepage: "https://github.com/OsgiliathEnterprise/nfs_client"
issues: "https://github.com/OsgiliathEnterprise/nfs_client/issues"

readme: "README.md"
license:
  - "Apache-2.0"
tags:
  - "freeipa"
  - "freeipa-server"
  - "nfs"
  - "automount"
  - "storage"
