---
- name: Nfs-client | add host to nfsclients group
  freeipa.ansible_freeipa.ipahostgroup:
    ipaadmin_password: "{{ company_realm_password }}"
    host:
      - "{{ hostname | default(volume_machine_hostname.stdout) }}"
    hostgroup:
      - nfsclients
    action: member
  failed_when: False
  changed_when: False
  become: True

- name: Nfs-client | iterate over mountpoints to configure automount
  ansible.builtin.include_tasks: nfs-client-automount-conf.yml
  loop: "{{ nfs_mountpoints }}"
  loop_control:
    loop_var: nfs_server

- name: Nfs-client | automount
  ansible.builtin.command: "ipa-client-automount -U"
  failed_when: False
  changed_when: False
  become: True

- name: Nfs-client | disable autofs # TODO test regularly if mountpoint works...
  ansible.builtin.systemd:
    name: "autofs"
    state: started
    enabled: True
  become: true

#- name: ansible-volumes | nfs-client | iterate over mountpoints to configure mount in fstab (while we are not able to configure autofs)
#  ansible.builtin.include_tasks: nfs-client-fstab-conf.yml
#  loop: "{{ nfs_mountpoints }}"
#  loop_control:
#    loop_var: nfs_server


- name: Nfs-client | configure kerb ticket auto renewal
  ansible.builtin.lineinfile:
    path: /etc/sssd/sssd.conf
    regexp: "{{ item.regexp }}"
    insertafter: '^\[domain/{{ company_domain }}\]'
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^krb5_renewable_lifetime = 50d', line: 'krb5_renewable_lifetime = 50d' }
    - { regexp: '^krb5_renew_interval = 3600', line: 'krb5_renew_interval = 3600' }
  become: true

- name: Nfs-client | restart sssd after modifications
  ansible.builtin.systemd:
    name: "sssd"
    state: restarted
    enabled: true
  become: true
