---

- name: Nfs-client-automount-entry | create libvirt conf folder
  ansible.builtin.file:
    state: directory
    dest: "{{ mounpoint.local }}"
    mode: "0755"
    owner: "root"
    group: "root"
  failed_when: False
  become: true

- name: Nfs-client-automount-entry | create automountmap for client
  ansible.builtin.shell: |
    set -o pipefail && echo '{{ company_realm_password }}' | kinit admin > /dev/null
    ipa automountmap-add default auto.{{ hostname | default(volume_machine_hostname.stdout) + '.' + mounpoint.local | replace('/', '') }}
  delegate_to: "{{ groups[idm_group][0] }}"
#    ipa automountmap-add {{ mounpoint.local | replace('/', '') }} auto.{{ mounpoint.local | replace('/', '') }}
  no_log: "{{ secure_logs }}"
  failed_when: False
  changed_when: False
  become: true

- name: Nfs-client-automount-entry | create automountkey on master
  ansible.builtin.shell: |
    set -o pipefail && echo '{{ company_realm_password }}' | kinit admin > /dev/null
    ipa automountkey-add default auto.master --key={{ mounpoint.local }} --info=auto.{{ hostname | default(volume_machine_hostname.stdout) + '.' + mounpoint.local | replace('/', '') }}
  delegate_to: "{{ groups[idm_group][0] }}"
  no_log: "{{ secure_logs }}"
  failed_when: False
  changed_when: False
  become: true

- name: Nfs-client-automount-entry | create automountkey for mountpoint
  ansible.builtin.shell: |
    set -o pipefail && echo '{{ company_realm_password }}' | kinit admin > /dev/null
    ipa automountkey-add default auto.{{ hostname | default(volume_machine_hostname.stdout) + '.' + mounpoint.local | replace('/', '') }} --key='*' --info="-fstype=nfs4,rw,sec=krb5p,soft,rsize=8192,wsize=8192 {{ nfs_server.host }}:{{ mounpoint.remote }}"
  delegate_to: "{{ groups[idm_group][0] }}" # the key was {{ hostname | default(volume_machine_hostname.stdout) }} but it was not really appealing for users
  no_log: "{{ secure_logs }}"
  failed_when: False
  changed_when: False
  notify: ansible-volumes | handler | reload-automount
  become: true
