---
# handlers file for lvm

- name: Handler | reload-automount
  ansible.builtin.shell: |
    set -o pipefail && echo '{{ company_realm_password }}' | kinit admin > /dev/null
    ipa-client-automount --uninstall
    ipa-client-automount --location=default -U
  become: true
  changed_when: false
  listen: nfs_client | handler | reload-automount

- name: Handler | refresh autofs
  ansible.builtin.service:
    name: "autofs"
    state: restarted
    enabled: True
  become: true
  changed_when: false
  listen: nfs_client | handler | reload-automount

- name: Handler | refresh automount
  ansible.builtin.shell: |
    set -o pipefail && echo '{{ company_realm_password }}' | kinit admin > /dev/null
    ipa-client-automount -U
  failed_when: false
  changed_when: false
  become: True
  listen: nfs_client | handler | reload-automount

- name: Handler | restart sssd after modifications
  ansible.builtin.systemd:
    name: "sssd"
    state: restarted
    enabled: true
  changed_when: false
  become: true
  listen: nfs_client | handler | reload-sssd
