---
dependency:
  name: galaxy
  enabled: ${DEPENDENCY_ENABLED:-True}
  options:
    role-file: ${REQUIREMENTS_PATH:-requirements-standalone.yml}
    roles-path: ${MOLECULE_PROJECT_DIRECTORY}/../community
    requirements-file: requirements-collections.yml
    collections-path: ${MOLECULE_PROJECT_DIRECTORY}/../community-collections
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: consumer.osgiliath.test
    box: ${TESTBOX:-fedora/38-cloud-base}
    provider_options:
      cpus: 2
      memory: 3096
    interfaces:
      - type: dhcp
        # ip: "192.168.56.5"
        auto_config: true
        network_name: private_network
        virtualbox__intnet: "internalnetwork"
    groups:
      - ipaservers
    provider_raw_config_args:
      - "customize ['storagectl', :id, '--name', 'IDE', '--hostiocache', 'on']"
  - name: datastore.osgiliath.test
    box: ${TESTBOX:-fedora/38-cloud-base}
    provider_options:
      cpus: 2
      memory: 2048
    interfaces:
      - type: dhcp
        # ip: "192.168.56.5"
        auto_config: true
        network_name: private_network
        virtualbox__intnet: "internalnetwork"
    groups:
      - ipaclients
    provider_raw_config_args:
      - "customize ['storagectl', :id, '--name', 'IDE', '--hostiocache', 'on']"
    provider_override_args:
      - "persistent_storage.enabled = true"
      - "persistent_storage.location = 'molecule-volumes.vdi'"
      - "persistent_storage.size = 10"
      - "persistent_storage.mount = false"
      - "persistent_storage.diskdevice = '/dev/sdb'"
provisioner:
  name: ansible
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
  options:
    v: 1
scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
#    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy