---
- name: prepare IPA
  hosts: consumer.osgiliath.test
  tasks:
    - include_role:
        name: tcharl.nfs_client
        tasks_from: requirements.yml
      vars:
        secure_logs: false
        preferred_nic: "eth1"
        company_domain: osgiliath.test
        allow_dns_zone_overlap: True
        company_realm_password: '123ADMin'
        company_ad_password: '123ADmPass'
- name: Expose NFS
  hosts: datastore.osgiliath.test
  vars:
    secure_logs: false
    company_domain: osgiliath.test
    company_realm_password: '123ADMin'
    company_ad_password: '123ADmPass'
    preferred_nic: "eth1"
    lvm_groups:
      - vgname: non-persistent
        disks:
          - /dev/sdb1
        create: true
        lvmetanames:
          - lvname: nfs_exposed
            size: 4M
            create: true
            filesystem: xfs
            expose_nfs: True
            mntp: /var/nfs
            mount: true
    manage_lvm: true
    configure_nfs: True
  roles:
    - role: tcharl.nfs_server
