---
- name: Consume NFS
  hosts: consumer.osgiliath.test
  vars:
    company_domain: osgiliath.test
    company_realm_password: '123ADMin'
    company_ad_password: '123ADmPass'
    configure_nfs: True
    nfs_mountpoints:
      - host: datastore.osgiliath.test
        mountpoints:
         - remote: /var/nfs
           local: /net
  roles:
    - role: tcharl.nfs_client
