---
- name: Consume NFS
  hosts: consumer.osgiliath.test
  vars:
    company_domain: osgiliath.test
    company_realm_password: '123ADMin'
    company_ad_password: '123ADmPass'
    configure_nfs: True
    preferred_nic: "eth1"
    standalone_role: False
    nfs_mountpoints:
      - host: datastore.osgiliath.test
        mountpoints:
         - remote: /var/nfs
           # insecure: yes, min_ip_to_share: 192.168.1.128
           local: /net
  roles:
    - role: tcharl.nfs_client
